### ISSUE TITLE
Development Pods support

### ISSUE THREAD

**Issue by d1mster** [peripheryapp/periphery#485]
Does library support development pods? I run script, it works properly, but periphery found unused code only in my main target.

**Comment by andraskadar** [comment]
Hi @d1mster!
I have just recently tried it and it works for me without issues. The only thing is that the `--setup` did not detect the target automatically. My yml file looks like this:
```yml
retain_public: true
schemes:
- DevelopmentPod
- SampleApp
targets:
- DevelopmentPod
- SampleApp
- SampleAppTests
- SampleAppUITests
workspace: Soteria/Soteria.xcworkspace
```
