### ISSUE TITLE
Reports func as unused but is literally used

### ISSUE THREAD

**Issue by nikolalukovic** [peripheryapp/periphery#631]
What am I doing wrong here?

### Contents of .periphery.yml (Using 2.14.1)
```yml
clean_build: true
project: Primal.xcodeproj
retain_objc_accessible: true
schemes:
- Primal
targets:
- Primal
- PrimalTests
```

![Screenshot 2023-07-03 at 16 40 11](https://github.com/peripheryapp/periphery/assets/6897673/37a11744-f5ea-4de1-8658-e8a9d1fafdb5)
